### ISSUE TITLE
TODO - Step 1

### ISSUE THREAD

**Issue by NicoLaval** [Making-Sense-Info/VTL-Docs#2]
- Docs
    - [ ] Complete `content` folder with nested json files (abs, clause, if, join, aggr)
    - [ ] produce a single JSON file
    - [ ] produce `sidebar.js`
    - [ ] produce /docs MD content
- Tests
    - [ ] include #1 test suite
